<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Version>1.1.0</Version>
    <Product>Pendulum</Product>
    <Company>Surmise</Company>
    <Copyright>Copyright © 2026 Darren Marshall</Copyright>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Resources\pendulum.ico</ApplicationIcon>
    <AssemblyName>Pendulum</AssemblyName>
    <RootNamespace>Pendulum.App</RootNamespace>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishSingleFile>false</PublishSingleFile>
    <Platforms>x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="H.NotifyIcon.Wpf" Version="2.2.0" />
    <PackageReference Include="WPF-UI" Version="3.0.5" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pendulum.Core\Pendulum.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\pendulum.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Resources\Sounds\*.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>Sounds\%(Filename)%(Extension)</Link>
    </None>
  </ItemGroup>

</Project>
